version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - ./tmp:/rails/tmp
      - ./log:/rails/log
      - bundle_cache:/usr/local/bundle
    environment:
      - RAILS_ENV=development
    command: ./bin/rails server -b 0.0.0.0

volumes:
  bundle_cache:
